name = "atbbs-opengraph"
main = "index.ts"
compatibility_date = "2026-09-05"

rules = [
  { type = "Text", globs = ["**/*.svg"], fallthrough = true }
]

[[routes]]
pattern = "*atbbs.xyz/bbs/*"
zone_name = "atbbs.xyz"

[[routes]]
pattern = "*atbbs.xyz/og/*"
zone_name = "atbbs.xyz"
